### ISSUE TITLE
Cannot use the CDN version of liff-mock

### ISSUE THREAD

**Issue by epaew** [line/liff-mock#5]
Hello.

I tried to use the CDN version of liff-mock, but it was not working.
`window.liffMock` property was found, but the value of `liffMock` is undefined.

## how to reproduce
Create the below HTML file, and open in web browser.
```html
<head>
  <script src="https://unpkg.com/@line/liff-mock@1.0.1/dist/umd/liff-mock.js"></script> <!-- same for 1.0.0-->
  <script>
    window.addEventListener('load', () => {
      console.debug(window.hasOwnProperty('liffMock')); // true
      console.debug(window.liffMock);                   // undefined
    });
  </script>
</head>
```

## how to escape
Use the npm version of liff-mock, it works.

Thanks,

**Comment by so99ynoodles** [comment]
@epaew 
Thank you for reporting the issue! 🙇 

@cola119 
I think this is because of `entry: './plugin.ts'` since this file doesn't use `default export`.
Changing it to `./index.ts` or using `default export` in `plugin.ts` will fix this issue I think.

**Comment by cola119** [comment]
Thank you for your reporting. Let me investigate.

**Comment by cola119** [comment]
It looks working fine since v1.0.2.

https://line.github.io/liff-mock/examples/cdn-example/

https://github.com/line/liff-mock/blob/595106446515a8d68c885f38c8c9ec225fbf5588/examples/cdn-example/index.html#L8-L13
https://github.com/line/liff-mock/blob/595106446515a8d68c885f38c8c9ec225fbf5588/examples/cdn-example/index.js#L1-L4
